name: Test Go build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code to a GOPATH compatible directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/c0_compiler

    - name: Display
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}
      env:
        GOPATH: /home/runner/work/c0_compiler/go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
      env:
        GOPATH: /home/runner/work/c0_compiler/go

    - name: Build
      run: go build -v .
      env:
        GOPATH: /home/runner/work/c0_compiler/go
